CREATE TABLE nhl_team_stats_single_season (
    id SERIAL PRIMARY KEY,
    team_id INT,
    team_name VARCHAR(255),
    games_played INT,
    wins INT,
    losses INT,
    ot INT,
    pts INT,
    pt_pctg DECIMAL(5,2),
    goals_per_game DECIMAL(5,4),
    goals_against_per_game DECIMAL(9,6),
    ev_gga_ratio DECIMAL(3,1),
    power_play_percentage DECIMAL(5,2),
    power_play_goals DECIMAL(5,1),
    power_play_goals_against DECIMAL(5,1),
    power_play_opportunities DECIMAL(5,1),
    penalty_kill_percentage DECIMAL(5,2),
    shots_per_game DECIMAL(7,4),
    shots_allowed DECIMAL(7,4),
    face_offs_taken DECIMAL(5,1),
    face_offs_won DECIMAL(5,1),
    face_offs_lost DECIMAL(5,1),
    face_off_win_percentage DECIMAL(5,2)
);
